package com.iteso.biblioteca.enums;

public enum Genero {
	NOVELA, POESIA, TEATRO, CUENTO, ENSAYO_LITERARIO, BIOGRAFIA, HISTORICA, FANTASIA, CIENCIA_FICCION, TERROR, ROMANCE,
	POLICIACA, AVENTURA, MITOLOGIA, INFANTIL, JUVENIL,

	CIENCIAS_COMPUTACION, MATEMATICAS, FISICA, QUIMICA, BIOLOGIA, INGENIERIA, MEDICINA, ARQUITECTURA, ECONOMIA, DERECHO,
	PSICOLOGIA, FILOSOFIA, SOCIOLOGIA,

	ARTE, MUSICA, CINE, FOTOGRAFIA, GASTRONOMIA, VIAJES,

	EDUCACION, IDIOMAS, ENCICLOPEDIA, DICCIONARIO,

	RELIGION, DEPORTES, JARDINERIA, AUTOAYUDA
}
