package com.iteso.biblioteca.enums;

public enum Puesto {
	BIBLIOTECARIO, ASISTENTE_BIBLIOTECA, CATALOGADOR, CONSERVADOR, SUPERVISOR, ADMINISTRADOR_SISTEMAS, REFERENCIA,
	RESTAURADOR, ARCHIVISTA, DIRECTOR;
}
