package com.iteso.biblioteca.enums;

public enum TematicaRevista {
	NOTICIAS_INTERNACIONALES, ACTUALIDAD_NACIONAL, POLITICA, ECONOMIA_MUNDIAL,

	TECNOLOGIA, INFORMATICA, GADGETS, VIDEOJUEGOS, CIENCIA,

	MODA, BELLEZA, DECORACION, GASTRONOMIA, VIAJES, SALUD_BIENESTAR, FITNESS,

	CINE_TV, MUSICA, ARTE_CULTURA, TEATRO_ESPECTACULOS, CELEBRIDADES, LITERATURA,

	NEGOCIOS, EDUCACION, MEDICINA_SALUD, DERECHO, PSICOLOGIA, ECOLOGIA,

	DEPORTES_GENERAL, FUTBOL, BALONCESTO, TENIS, AUTOMOVILISMO, DEPORTES_EXTREMOS,

	JARDINERIA, MASCOTAS, BODAS_EVENTOS, INFANTIL, JUVENIL, HISTORIA,

	COMUNIDAD_LOCAL, TURISMO_REGIONAL
}